platformName: Android
# 真机
platformVersion: 7.1.1
deviceName: July_Emulator
noReset: True
noSign: True
unicodeKeyBoard: True
resetKeyboard: True
appPackage: esunny.test
appActivity: com.esunny.estar.StartActivity
ip: 127.0.0.1
port: 4723